import AuthProvider from "../../components/AuthProvider/AuthProvider";
import Navbar from "../../components/Navbar/Navbar";
import Footer from "../../components/footer/Footer";
import { ThemeProvider } from "./context/ThemeContextProvider";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NEXT BLOG APP ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <div className="container">
              <Navbar />
              {children}
              <Footer />
            </div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
